dist: trusty

sudo: false

services:
- mysql

matrix:
  fast_finish: true

  include:
    - language: php
      php: 7.1
      env: PHPUNIT=1 DB_USERNAME=root
    - language: php
      php: 7.2
      env: PHPUNIT=1 DB_USERNAME=root

install:
- if [[ $PHPUNIT = 1 ]]; then composer install; fi

before_script:
- if [[ $PHPUNIT = 1 ]]; then sh -c "mysql -e 'CREATE DATABASE IF NOT EXISTS test_school_rankings;'"; fi
- if [[ $PHPUNIT = 1 ]]; then composer run-script post-install-cmd --no-interaction; fi

script:
- if [[ $PHPUNIT = 1 ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi
- if [[ $PHPUNIT = 1 ]]; then mkdir -p build/logs; fi

notifications:
  email: false
